"""add_password_fields_and_events

Revision ID: 18b0756de278
Revises: 3ef57f92c56b
Create Date: 2026-04-02 17:50:09.985961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b0756de278'
down_revision: Union[str, None] = '3ef57f92c56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Lógica Idempotente para Sincronización ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # 1. Crear el tipo ENUM para solicitudes si no existe
    # Nota: ENUMs en Postgres son tipos de datos globales y no tablas
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'solicitud_estado') THEN CREATE TYPE solicitud_estado AS ENUM ('pendiente', 'aprobada', 'aprobada_parcial', 'denegada'); END IF; END $$;")

    # 2. Crear tablas nuevas para Alcabalas y Eventos (solo si no existen)
    if 'puntos_acceso' not in tables:
        op.create_table('puntos_acceso',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('nombre', sa.String(length=200), nullable=False),
            sa.Column('ubicacion', sa.Text(), nullable=True),
            sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
            sa.PrimaryKeyConstraint('id')
        )

    if 'solicitudes_evento' not in tables:
        op.create_table('solicitudes_evento',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('entidad_id', sa.UUID(), nullable=False),
            sa.Column('solicitado_por', sa.UUID(), nullable=False),
            sa.Column('nombre_evento', sa.String(length=200), nullable=False),
            sa.Column('fecha_evento', sa.Date(), nullable=False),
            sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
            sa.Column('cantidad_aprobada', sa.Integer(), nullable=True),
            sa.Column('motivo', sa.Text(), nullable=False),
            sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'aprobada_parcial', 'denegada', name='solicitud_estado'), nullable=True, server_default=sa.text("'pendiente'")),
            sa.Column('revisado_por', sa.UUID(), nullable=True),
            sa.Column('motivo_rechazo', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
            sa.Column('revisado_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='RESTRICT'),
            sa.ForeignKeyConstraint(['revisado_por'], ['usuarios.id'], ondelete='RESTRICT'),
            sa.ForeignKeyConstraint(['solicitado_por'], ['usuarios.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('id')
        )

    # 3. Agregar columnas a la tabla 'usuarios' (solo si no existen)
    user_columns = [c['name'] for c in inspector.get_columns('usuarios')]
    if 'debe_cambiar_password' not in user_columns:
        op.add_column('usuarios', sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    if 'expira_at' not in user_columns:
        op.add_column('usuarios', sa.Column('expira_at', sa.DateTime(timezone=True), nullable=True))

    # 4. Agregar columna a 'codigos_qr' (solo si no existe)
    qr_columns = [c['name'] for c in inspector.get_columns('codigos_qr')]
    if 'solicitud_id' not in qr_columns:
        op.add_column('codigos_qr', sa.Column('solicitud_id', sa.UUID(), nullable=True))
        # Intentar crear FK solo si no existe o confiar en que no existe si la columna no estaba
        op.create_foreign_key('fk_codigos_qr_solicitud', 'codigos_qr', 'solicitudes_evento', ['solicitud_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Para el downgrade, intentamos borrar lo que encontremos
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'codigos_qr' in tables:
        qr_columns = [c['name'] for c in inspector.get_columns('codigos_qr')]
        if 'solicitud_id' in qr_columns:
            op.drop_constraint('fk_codigos_qr_solicitud', 'codigos_qr', type_='foreignkey')
            op.drop_column('codigos_qr', 'solicitud_id')

    if 'usuarios' in tables:
        user_columns = [c['name'] for c in inspector.get_columns('usuarios')]
        if 'expira_at' in user_columns:
            op.drop_column('usuarios', 'expira_at')
        if 'debe_cambiar_password' in user_columns:
            op.drop_column('usuarios', 'debe_cambiar_password')

    if 'solicitudes_evento' in tables:
        op.drop_table('solicitudes_evento')
    if 'puntos_acceso' in tables:
        op.drop_table('puntos_acceso')
    
    op.execute("DROP TYPE IF EXISTS solicitud_estado;")
    # ### end Alembic commands ###
