"""add_tipo_acceso_custom_to_lote

Revision ID: 1f293d6176ad
Revises: b2c3d4e5f6a1
Create Date: 2026-04-20 02:34:48.046116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f293d6176ad'
down_revision: Union[str, None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes_pase_masivo', sa.Column('tipo_acceso_custom_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lotes_pase_masivo', 'tipos_acceso_custom', ['tipo_acceso_custom_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lotes_pase_masivo', type_='foreignkey')
    op.drop_column('lotes_pase_masivo', 'tipo_acceso_custom_id')
    # ### end Alembic commands ###
