"""Add vehiculo_pase_id to_acceso

Revision ID: 27f2b5c8c1ea
Revises: 539b9a694fb3
Create Date: 2026-04-23 14:27:03.332230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f2b5c8c1ea'
down_revision: Union[str, None] = '539b9a694fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accesos', sa.Column('vehiculo_pase_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'accesos', 'vehiculos_pase', ['vehiculo_pase_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accesos', type_='foreignkey')
    op.drop_column('accesos', 'vehiculo_pase_id')
    # ### end Alembic commands ###
