"""Add Aegis Tactic design columns

Revision ID: 3383b4bbb80b
Revises: 34ebabc52fb4
Create Date: 2026-04-28 02:21:37.805650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3383b4bbb80b'
down_revision: Union[str, None] = '34ebabc52fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zonas_estacionamiento', sa.Column('config_ia', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('zonas_estacionamiento', sa.Column('grilla_tactica', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zonas_estacionamiento', 'grilla_tactica')
    op.drop_column('zonas_estacionamiento', 'config_ia')
    # ### end Alembic commands ###
