"""add_combustible_aegis_fuel

Revision ID: 3484dc14b07e
Revises: 408b17c09b1f
Create Date: 2026-05-31 15:12:36.653435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3484dc14b07e'
down_revision: Union[str, None] = '408b17c09b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear tipos enum explícitamente en PostgreSQL antes de usarlos en tablas existentes
    uso_vehiculo_tipo = sa.Enum('particular', 'protocolar', 'servicio', name='uso_vehiculo_tipo')
    uso_vehiculo_tipo.create(op.get_bind(), checkfirst=True)
    
    tipo_combustible_enum = sa.Enum('gasolina', 'diesel', name='tipo_combustible_enum')
    tipo_combustible_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('tanques_combustible',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_combustible', sa.Enum('gasolina', 'diesel', name='tipo_combustible_tanque'), nullable=False),
    sa.Column('capacidad_maxima', sa.Float(), nullable=False),
    sa.Column('cantidad_actual', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas_tanque',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tanque_id', sa.UUID(), nullable=False),
    sa.Column('bombero_id', sa.UUID(), nullable=False),
    sa.Column('tipo_lectura', sa.Enum('inicial_semana', 'recarga_externa', 'ajuste_auditoria', name='tipo_lectura_tanque_enum'), nullable=False),
    sa.Column('cantidad_medida', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bombero_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tanque_id'], ['tanques_combustible.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes_combustible',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=True),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('bombero_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Float(), nullable=False),
    sa.Column('tipo_solicitud', sa.Enum('limite_entidad_excedido', 'vehiculo_no_autorizado', 'vehiculo_no_registrado', name='tipo_solicitud_comb_enum'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', 'consumida', name='estado_solicitud_comb_enum'), nullable=False),
    sa.Column('nombre_conductor_manual', sa.String(length=200), nullable=True),
    sa.Column('cedula_conductor_manual', sa.String(length=100), nullable=True),
    sa.Column('marca_manual', sa.String(length=100), nullable=True),
    sa.Column('modelo_manual', sa.String(length=100), nullable=True),
    sa.Column('color_manual', sa.String(length=50), nullable=True),
    sa.Column('aprobado_por_id', sa.UUID(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bombero_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abastecimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=False),
    sa.Column('bombero_id', sa.UUID(), nullable=False),
    sa.Column('tanque_id', sa.UUID(), nullable=False),
    sa.Column('kilometraje_anterior', sa.Integer(), nullable=False),
    sa.Column('kilometraje_actual', sa.Integer(), nullable=False),
    sa.Column('cantidad_abastecida', sa.Float(), nullable=False),
    sa.Column('foto_kilometraje_url', sa.Text(), nullable=False),
    sa.Column('foto_maquina_url', sa.Text(), nullable=False),
    sa.Column('datos_ia_ocr', sa.JSON(), nullable=True),
    sa.Column('tiene_alerta', sa.Boolean(), nullable=False),
    sa.Column('solicitud_aprobacion_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bombero_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitud_aprobacion_id'], ['solicitudes_combustible.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tanque_id'], ['tanques_combustible.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entidades_civiles', sa.Column('limite_combustible_semanal', sa.Float(), server_default='0.0', nullable=False))
    op.drop_constraint(op.f('infracciones_puesto_id_fkey'), 'infracciones', type_='foreignkey')
    op.create_foreign_key(None, 'infracciones', 'puestos_estacionamiento', ['puesto_id'], ['id'], ondelete='SET NULL')
    op.add_column('vehiculos', sa.Column('entidad_id', sa.UUID(), nullable=True))
    op.add_column('vehiculos', sa.Column('uso_vehiculo', sa.Enum('particular', 'protocolar', 'servicio', name='uso_vehiculo_tipo'), server_default='particular', nullable=False))
    op.add_column('vehiculos', sa.Column('autorizado_combustible', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('vehiculos', sa.Column('tipo_combustible', sa.Enum('gasolina', 'diesel', name='tipo_combustible_enum'), server_default='gasolina', nullable=False))
    op.add_column('vehiculos', sa.Column('capacidad_tanque', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('vehiculos', sa.Column('asignacion_combustible_semanal', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('vehiculos', sa.Column('ultimo_kilometraje', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key(None, 'vehiculos', 'entidades_civiles', ['entidad_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('vehiculos_pase_puesto_asignado_id_fkey'), 'vehiculos_pase', type_='foreignkey')
    op.create_foreign_key(None, 'vehiculos_pase', 'puestos_estacionamiento', ['puesto_asignado_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehiculos_pase', type_='foreignkey')
    op.create_foreign_key(op.f('vehiculos_pase_puesto_asignado_id_fkey'), 'vehiculos_pase', 'puestos_estacionamiento', ['puesto_asignado_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'vehiculos', type_='foreignkey')
    op.drop_column('vehiculos', 'ultimo_kilometraje')
    op.drop_column('vehiculos', 'asignacion_combustible_semanal')
    op.drop_column('vehiculos', 'capacidad_tanque')
    op.drop_column('vehiculos', 'tipo_combustible')
    op.drop_column('vehiculos', 'autorizado_combustible')
    op.drop_column('vehiculos', 'uso_vehiculo')
    op.drop_column('vehiculos', 'entidad_id')
    op.drop_constraint(None, 'infracciones', type_='foreignkey')
    op.create_foreign_key(op.f('infracciones_puesto_id_fkey'), 'infracciones', 'puestos_estacionamiento', ['puesto_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('entidades_civiles', 'limite_combustible_semanal')
    op.drop_table('abastecimientos')
    op.drop_table('solicitudes_combustible')
    op.drop_table('lecturas_tanque')
    op.drop_table('tanques_combustible')
    
    # Eliminar tipos enum creados manualmente
    sa.Enum(name='uso_vehiculo_tipo').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='tipo_combustible_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
