"""Add polygon and area fields to zones

Revision ID: 34ebabc52fb4
Revises: 92bf76acf45a
Create Date: 2026-04-27 23:34:32.813418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34ebabc52fb4'
down_revision: Union[str, None] = '92bf76acf45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zonas_estacionamiento', sa.Column('poligono', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('zonas_estacionamiento', sa.Column('area_m2', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('zonas_estacionamiento', sa.Column('capacidad_sugerida_ia', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zonas_estacionamiento', 'capacidad_sugerida_ia')
    op.drop_column('zonas_estacionamiento', 'area_m2')
    op.drop_column('zonas_estacionamiento', 'poligono')
    # ### end Alembic commands ###
