"""Init

Revision ID: 3ef57f92c56b
Revises: 
Create Date: 2026-03-30 21:55:55.068638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef57f92c56b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_index(op.f('ix_configuracion_clave'), 'configuracion', ['clave'], unique=False)
    op.create_table('zonas_estacionamiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('capacidad_total', sa.Integer(), nullable=False),
    sa.Column('ocupacion_actual', sa.Integer(), nullable=False),
    sa.Column('descripcion_ubicacion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('entidades_civiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo_slug', sa.String(length=50), nullable=False),
    sa.Column('zona_id', sa.UUID(), nullable=True),
    sa.Column('capacidad_vehiculos', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas_estacionamiento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entidades_civiles_codigo_slug'), 'entidades_civiles', ['codigo_slug'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.Enum('COMANDANTE', 'ADMIN_BASE', 'SUPERVISOR', 'ALCABALA', 'ADMIN_ENTIDAD', 'PARQUERO', 'SOCIO', name='rol_tipo'), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_foreign_key('fk_entidades_civiles_created_by', 'entidades_civiles', 'usuarios', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_table('vehiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['socio_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_table('infracciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('reportado_por', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('mal_estacionado', 'exceso_velocidad', 'conducta_indebida', 'documentos_vencidos', 'otro', name='infraccion_tipo'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('bloquea_salida', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'resuelta', 'perdonada', name='infraccion_estado'), nullable=False),
    sa.Column('resuelta_por', sa.UUID(), nullable=True),
    sa.Column('resuelta_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones_resolucion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reportado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resuelta_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infracciones_estado'), 'infracciones', ['estado'], unique=False)
    op.create_index(op.f('ix_infracciones_usuario_id'), 'infracciones', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_infracciones_vehiculo_id'), 'infracciones', ['vehiculo_id'], unique=False)
    op.create_table('membresias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=True),
    sa.Column('cupo_numero', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'suspendida', 'vencida', name='membresia_estado'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['socio_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membresias_entidad_id'), 'membresias', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_membresias_socio_id'), 'membresias', ['socio_id'], unique=False)
    op.create_table('codigos_qr',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=True),
    sa.Column('membresia_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('permanente', 'temporal', name='qr_tipo'), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_qr_token'), 'codigos_qr', ['token'], unique=True)
    op.create_index(op.f('ix_codigos_qr_usuario_id'), 'codigos_qr', ['usuario_id'], unique=False)
    op.create_table('accesos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qr_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('entrada', 'salida', name='acceso_tipo'), nullable=False),
    sa.Column('punto_acceso', sa.String(length=100), nullable=False),
    sa.Column('registrado_por', sa.UUID(), nullable=False),
    sa.Column('es_manual', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['codigos_qr.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesos_registrado_por'), 'accesos', ['registrado_por'], unique=False)
    op.create_index(op.f('ix_accesos_timestamp'), 'accesos', ['timestamp'], unique=False)
    op.create_index(op.f('ix_accesos_usuario_id'), 'accesos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_entidades_civiles_created_by', 'entidades_civiles', type_='foreignkey')
    op.drop_index(op.f('ix_accesos_usuario_id'), table_name='accesos')
    op.drop_index(op.f('ix_accesos_timestamp'), table_name='accesos')
    op.drop_index(op.f('ix_accesos_registrado_por'), table_name='accesos')
    op.drop_table('accesos')
    op.drop_index(op.f('ix_codigos_qr_usuario_id'), table_name='codigos_qr')
    op.drop_index(op.f('ix_codigos_qr_token'), table_name='codigos_qr')
    op.drop_table('codigos_qr')
    op.drop_index(op.f('ix_membresias_socio_id'), table_name='membresias')
    op.drop_index(op.f('ix_membresias_entidad_id'), table_name='membresias')
    op.drop_table('membresias')
    op.drop_index(op.f('ix_infracciones_vehiculo_id'), table_name='infracciones')
    op.drop_index(op.f('ix_infracciones_usuario_id'), table_name='infracciones')
    op.drop_index(op.f('ix_infracciones_estado'), table_name='infracciones')
    op.drop_table('infracciones')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_entidades_civiles_codigo_slug'), table_name='entidades_civiles')
    op.drop_table('entidades_civiles')
    op.drop_table('zonas_estacionamiento')
    op.drop_index(op.f('ix_configuracion_clave'), table_name='configuracion')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
