"""vehiculos_y_infracciones_huerfanos

Revision ID: 4a756f389208
Revises: a9f1b2c3d4e5
Create Date: 2026-05-04 17:05:47.640556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a756f389208'
down_revision: Union[str, None] = 'a9f1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_accesos_zona_id', table_name='accesos')
    op.create_index(op.f('ix_accesos_zona_id'), 'accesos', ['zona_id'], unique=False)
    op.alter_column('infracciones', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_membresias_zona_id', table_name='membresias')
    op.alter_column('vehiculos', 'socio_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehiculos', 'socio_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_membresias_zona_id', 'membresias', ['zona_id'], unique=False)
    op.alter_column('infracciones', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_accesos_zona_id'), table_name='accesos')
    op.create_index('idx_accesos_zona_id', 'accesos', ['zona_id'], unique=False)
    # ### end Alembic commands ###
