"""Add ConfiguracionCorreo

Revision ID: 4d951c246c9f
Revises: e44733fda187
Create Date: 2026-04-25 22:37:00.795506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d951c246c9f'
down_revision: Union[str, None] = 'e44733fda187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_correo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('proveedor', sa.String(length=50), nullable=False),
    sa.Column('api_key_resend', sa.String(length=255), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('nombre_remitente', sa.String(length=100), nullable=True),
    sa.Column('email_remitente', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entidad_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion_correo')
    # ### end Alembic commands ###
