"""make_acceso_usuario_id_nullable

Revision ID: 539b9a694fb3
Revises: c4cfe591bf8c
Create Date: 2026-04-23 13:16:47.674038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539b9a694fb3'
down_revision: Union[str, None] = 'c4cfe591bf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accesos', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accesos', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
