"""BAGFM v2.0 Tactical Evolution Models

Revision ID: 83d690a8b1d4
Revises: f9a2b1c9b3d8
Create Date: 2026-04-18 20:05:47.507194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d690a8b1d4'
down_revision: Union[str, None] = 'f9a2b1c9b3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puestos_estacionamiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zona_id', sa.UUID(), nullable=False),
    sa.Column('numero_puesto', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Enum('libre', 'ocupado', 'reservado', 'reservado_base', 'mantenimiento', name='estado_puesto'), nullable=False),
    sa.Column('reservado_base', sa.Boolean(), nullable=False),
    sa.Column('reservado_entidad_id', sa.UUID(), nullable=True),
    sa.Column('vehiculo_actual_id', sa.UUID(), nullable=True),
    sa.Column('qr_actual_id', sa.UUID(), nullable=True),
    sa.Column('ocupado_desde', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qr_actual_id'], ['codigos_qr.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservado_entidad_id'], ['entidades_civiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehiculo_actual_id'], ['vehiculos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas_estacionamiento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puestos_estacionamiento_estado'), 'puestos_estacionamiento', ['estado'], unique=False)
    op.create_index(op.f('ix_puestos_estacionamiento_zona_id'), 'puestos_estacionamiento', ['zona_id'], unique=False)
    op.create_table('asignaciones_zona',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zona_id', sa.UUID(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('capacidad_asignada', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas_estacionamiento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_zona_entidad_id'), 'asignaciones_zona', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_zona_zona_id'), 'asignaciones_zona', ['zona_id'], unique=False)
    op.create_table('incentivos_parquero',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parquero_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('bono_eficiencia', 'reconocimiento', 'dia_libre', 'ascenso', name='tipo_incentivo'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('otorgado_por', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['otorgado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parquero_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incentivos_parquero_parquero_id'), 'incentivos_parquero', ['parquero_id'], unique=False)
    op.create_table('mensajes_broadcast',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('enviado_por', sa.UUID(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('destinatarios', sa.String(length=50), nullable=False),
    sa.Column('leido_por', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_broadcast_entidad_id'), 'mensajes_broadcast', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_mensajes_broadcast_enviado_por'), 'mensajes_broadcast', ['enviado_por'], unique=False)
    op.create_table('plantillas_carnet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_carnet', sa.Enum('colgante', 'cartera', 'ticket', 'credencial', name='tipo_carnet'), nullable=False),
    sa.Column('tipo_pase', sa.Enum('simple', 'identificado', 'portal', name='passe_tipo_enum'), nullable=True),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=False),
    sa.Column('color_secundario', sa.String(length=7), nullable=False),
    sa.Column('color_texto', sa.String(length=7), nullable=False),
    sa.Column('fondo_url', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('mostrar_foto', sa.Boolean(), nullable=False),
    sa.Column('mostrar_vehiculo', sa.Boolean(), nullable=False),
    sa.Column('mostrar_qr', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_carnet_entidad_id'), 'plantillas_carnet', ['entidad_id'], unique=False)
    op.create_table('sanciones_parquero',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parquero_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('amonestacion', 'suspension_temporal', 'relevo_inmediato', 'reportar_autoridades', name='tipo_sancion'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'cumplida', 'apelada', name='estado_sancion'), nullable=False),
    sa.Column('ejecutar_inmediato', sa.Boolean(), nullable=False),
    sa.Column('sancionado_por', sa.UUID(), nullable=False),
    sa.Column('resuelto_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parquero_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sancionado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanciones_parquero_estado'), 'sanciones_parquero', ['estado'], unique=False)
    op.create_index(op.f('ix_sanciones_parquero_parquero_id'), 'sanciones_parquero', ['parquero_id'], unique=False)
    op.create_table('tipos_acceso_custom',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('nivel_prioridad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_civiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_acceso_custom_entidad_id'), 'tipos_acceso_custom', ['entidad_id'], unique=False)
    op.create_table('vehiculos_pase',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qr_id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('zona_asignada_id', sa.UUID(), nullable=True),
    sa.Column('puesto_asignado_id', sa.UUID(), nullable=True),
    sa.Column('ingresado', sa.Boolean(), nullable=False),
    sa.Column('hora_ingreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['puesto_asignado_id'], ['puestos_estacionamiento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qr_id'], ['codigos_qr.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zona_asignada_id'], ['zonas_estacionamiento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_pase_qr_id'), 'vehiculos_pase', ['qr_id'], unique=False)
    
    from sqlalchemy.dialects import postgresql
    tipo_acceso_pase = postgresql.ENUM('logistica', 'prensa', 'vip', 'general', 'staff', 'artista', 'custom', name='tipo_acceso_pase')
    tipo_acceso_pase.create(op.get_bind(), checkfirst=True)
    
    gravedad_infraccion = postgresql.ENUM('leve', 'moderada', 'grave', 'critica', name='gravedad_infraccion')
    gravedad_infraccion.create(op.get_bind(), checkfirst=True)
    op.add_column('codigos_qr', sa.Column('tipo_acceso', sa.Enum('logistica', 'prensa', 'vip', 'general', 'staff', 'artista', 'custom', name='tipo_acceso_pase'), nullable=False, server_default='general'))
    op.add_column('codigos_qr', sa.Column('tipo_acceso_custom_id', sa.UUID(), nullable=True))
    op.add_column('codigos_qr', sa.Column('zona_asignada_id', sa.UUID(), nullable=True))
    op.add_column('codigos_qr', sa.Column('puesto_asignado_id', sa.UUID(), nullable=True))
    op.add_column('codigos_qr', sa.Column('nombre_portador', sa.String(length=200), nullable=True))
    op.add_column('codigos_qr', sa.Column('cedula_portador', sa.String(length=20), nullable=True))
    op.add_column('codigos_qr', sa.Column('vehiculo_placa', sa.String(length=20), nullable=True))
    op.add_column('codigos_qr', sa.Column('multi_vehiculo', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('codigos_qr', sa.Column('datos_completos', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('codigos_qr', sa.Column('verificado_por_parquero', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('codigos_qr', sa.Column('hora_entrada_base', sa.DateTime(timezone=True), nullable=True))
    op.add_column('codigos_qr', sa.Column('hora_llegada_zona', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'codigos_qr', 'puestos_estacionamiento', ['puesto_asignado_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'codigos_qr', 'tipos_acceso_custom', ['tipo_acceso_custom_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'codigos_qr', 'zonas_estacionamiento', ['zona_asignada_id'], ['id'], ondelete='RESTRICT')
    op.add_column('entidades_civiles', sa.Column('cuota_pases_autonoma', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('infracciones', sa.Column('gravedad', sa.Enum('leve', 'moderada', 'grave', 'critica', name='gravedad_infraccion'), nullable=False, server_default='leve'))
    op.add_column('infracciones', sa.Column('fotos_evidencia', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('infracciones', sa.Column('bloquea_acceso_futuro', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('infracciones', sa.Column('suspendido_hasta', sa.DateTime(timezone=True), nullable=True))
    op.add_column('infracciones', sa.Column('zona_id', sa.UUID(), nullable=True))
    op.add_column('infracciones', sa.Column('puesto_id', sa.UUID(), nullable=True))
    op.add_column('infracciones', sa.Column('entidad_id', sa.UUID(), nullable=True))
    op.add_column('infracciones', sa.Column('latitud_infraccion', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('infracciones', sa.Column('longitud_infraccion', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('infracciones', sa.Column('notas_internas', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'infracciones', 'puestos_estacionamiento', ['puesto_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'infracciones', 'entidades_civiles', ['entidad_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'infracciones', 'zonas_estacionamiento', ['zona_id'], ['id'], ondelete='RESTRICT')
    op.add_column('lotes_pase_masivo', sa.Column('entidad_id', sa.UUID(), nullable=True))
    op.add_column('lotes_pase_masivo', sa.Column('tipo_acceso', sa.Enum('logistica', 'prensa', 'vip', 'general', 'staff', 'artista', 'custom', name='tipo_acceso_pase'), nullable=False, server_default='general'))
    op.add_column('lotes_pase_masivo', sa.Column('requiere_aprobacion', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('lotes_pase_masivo', sa.Column('aprobado_por', sa.UUID(), nullable=True))
    op.add_column('lotes_pase_masivo', sa.Column('zona_estacionamiento_id', sa.UUID(), nullable=True))
    op.add_column('lotes_pase_masivo', sa.Column('plantilla_carnet_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lotes_pase_masivo', 'zonas_estacionamiento', ['zona_estacionamiento_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lotes_pase_masivo', 'entidades_civiles', ['entidad_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lotes_pase_masivo', 'plantillas_carnet', ['plantilla_carnet_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lotes_pase_masivo', 'usuarios', ['aprobado_por'], ['id'], ondelete='RESTRICT')
    op.add_column('usuarios', sa.Column('zona_asignada_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'zonas_estacionamiento', ['zona_asignada_id'], ['id'], ondelete='RESTRICT')
    op.add_column('zonas_estacionamiento', sa.Column('usa_puestos_identificados', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('zonas_estacionamiento', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('zonas_estacionamiento', sa.Column('punto_acceso_lat', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('zonas_estacionamiento', sa.Column('punto_acceso_lon', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('zonas_estacionamiento', sa.Column('tiempo_limite_llegada_min', sa.Integer(), nullable=False, server_default='15'))
    op.add_column('zonas_estacionamiento', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'zonas_estacionamiento', 'usuarios', ['created_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zonas_estacionamiento', type_='foreignkey')
    op.drop_column('zonas_estacionamiento', 'created_by')
    op.drop_column('zonas_estacionamiento', 'tiempo_limite_llegada_min')
    op.drop_column('zonas_estacionamiento', 'punto_acceso_lon')
    op.drop_column('zonas_estacionamiento', 'punto_acceso_lat')
    op.drop_column('zonas_estacionamiento', 'tipo')
    op.drop_column('zonas_estacionamiento', 'usa_puestos_identificados')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'zona_asignada_id')
    op.drop_constraint(None, 'lotes_pase_masivo', type_='foreignkey')
    op.drop_constraint(None, 'lotes_pase_masivo', type_='foreignkey')
    op.drop_constraint(None, 'lotes_pase_masivo', type_='foreignkey')
    op.drop_constraint(None, 'lotes_pase_masivo', type_='foreignkey')
    op.drop_column('lotes_pase_masivo', 'plantilla_carnet_id')
    op.drop_column('lotes_pase_masivo', 'zona_estacionamiento_id')
    op.drop_column('lotes_pase_masivo', 'aprobado_por')
    op.drop_column('lotes_pase_masivo', 'requiere_aprobacion')
    op.drop_column('lotes_pase_masivo', 'tipo_acceso')
    op.drop_column('lotes_pase_masivo', 'entidad_id')
    op.drop_constraint(None, 'infracciones', type_='foreignkey')
    op.drop_constraint(None, 'infracciones', type_='foreignkey')
    op.drop_constraint(None, 'infracciones', type_='foreignkey')
    op.drop_column('infracciones', 'notas_internas')
    op.drop_column('infracciones', 'longitud_infraccion')
    op.drop_column('infracciones', 'latitud_infraccion')
    op.drop_column('infracciones', 'entidad_id')
    op.drop_column('infracciones', 'puesto_id')
    op.drop_column('infracciones', 'zona_id')
    op.drop_column('infracciones', 'suspendido_hasta')
    op.drop_column('infracciones', 'bloquea_acceso_futuro')
    op.drop_column('infracciones', 'fotos_evidencia')
    op.drop_column('infracciones', 'gravedad')
    op.drop_column('entidades_civiles', 'cuota_pases_autonoma')
    op.drop_constraint(None, 'codigos_qr', type_='foreignkey')
    op.drop_constraint(None, 'codigos_qr', type_='foreignkey')
    op.drop_constraint(None, 'codigos_qr', type_='foreignkey')
    op.drop_column('codigos_qr', 'hora_llegada_zona')
    op.drop_column('codigos_qr', 'hora_entrada_base')
    op.drop_column('codigos_qr', 'verificado_por_parquero')
    op.drop_column('codigos_qr', 'datos_completos')
    op.drop_column('codigos_qr', 'multi_vehiculo')
    op.drop_column('codigos_qr', 'vehiculo_placa')
    op.drop_column('codigos_qr', 'cedula_portador')
    op.drop_column('codigos_qr', 'nombre_portador')
    op.drop_column('codigos_qr', 'puesto_asignado_id')
    op.drop_column('codigos_qr', 'zona_asignada_id')
    op.drop_column('codigos_qr', 'tipo_acceso_custom_id')
    op.drop_column('codigos_qr', 'tipo_acceso')
    op.drop_index(op.f('ix_vehiculos_pase_qr_id'), table_name='vehiculos_pase')
    op.drop_table('vehiculos_pase')
    op.drop_index(op.f('ix_tipos_acceso_custom_entidad_id'), table_name='tipos_acceso_custom')
    op.drop_table('tipos_acceso_custom')
    op.drop_index(op.f('ix_sanciones_parquero_parquero_id'), table_name='sanciones_parquero')
    op.drop_index(op.f('ix_sanciones_parquero_estado'), table_name='sanciones_parquero')
    op.drop_table('sanciones_parquero')
    op.drop_index(op.f('ix_plantillas_carnet_entidad_id'), table_name='plantillas_carnet')
    op.drop_table('plantillas_carnet')
    op.drop_index(op.f('ix_mensajes_broadcast_enviado_por'), table_name='mensajes_broadcast')
    op.drop_index(op.f('ix_mensajes_broadcast_entidad_id'), table_name='mensajes_broadcast')
    op.drop_table('mensajes_broadcast')
    op.drop_index(op.f('ix_incentivos_parquero_parquero_id'), table_name='incentivos_parquero')
    op.drop_table('incentivos_parquero')
    op.drop_index(op.f('ix_asignaciones_zona_zona_id'), table_name='asignaciones_zona')
    op.drop_index(op.f('ix_asignaciones_zona_entidad_id'), table_name='asignaciones_zona')
    op.drop_table('asignaciones_zona')
    op.drop_index(op.f('ix_puestos_estacionamiento_zona_id'), table_name='puestos_estacionamiento')
    op.drop_index(op.f('ix_puestos_estacionamiento_estado'), table_name='puestos_estacionamiento')
    op.drop_table('puestos_estacionamiento')
    # ### end Alembic commands ###
