"""cambio_ondelete_acceso_set_null

Revision ID: 92bf76acf45a
Revises: 4d951c246c9f
Create Date: 2026-04-26 02:25:40.364755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bf76acf45a'
down_revision: Union[str, None] = '4d951c246c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accesos_qr_id_fkey', 'accesos', type_='foreignkey')
    op.create_foreign_key(None, 'accesos', 'codigos_qr', ['qr_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accesos', type_='foreignkey')
    op.create_foreign_key('accesos_qr_id_fkey', 'accesos', 'codigos_qr', ['qr_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
