"""add_tipo_acceso_id_to_puestos

Revision ID: ab9f9d3f1952
Revises: c3cafc41d2e3
Create Date: 2026-04-19 15:01:02.069278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9f9d3f1952'
down_revision: Union[str, None] = 'c3cafc41d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puestos_estacionamiento', sa.Column('tipo_acceso_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'puestos_estacionamiento', 'tipos_acceso_custom', ['tipo_acceso_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puestos_estacionamiento', type_='foreignkey')
    op.drop_column('puestos_estacionamiento', 'tipo_acceso_id')
    # ### end Alembic commands ###
