"""add hora_salida to vehiculo_pase

Revision ID: b0daf187814c
Revises: 27f2b5c8c1ea
Create Date: 2026-04-23 18:58:05.995655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0daf187814c'
down_revision: Union[str, None] = '27f2b5c8c1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos_pase', sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('vehiculos_pase', 'qr_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehiculos_pase', 'qr_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('vehiculos_pase', 'hora_salida')
    # ### end Alembic commands ###
