"""add_distribucion_cupos

Revision ID: c3cafc41d2e3
Revises: 9b5c9b9019e2
Create Date: 2026-04-19 13:03:33.974921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3cafc41d2e3'
down_revision: Union[str, None] = '9b5c9b9019e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones_zona', sa.Column('distribucion_cupos', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignaciones_zona', 'distribucion_cupos')
    # ### end Alembic commands ###
