"""add_massive_events_models

Revision ID: d8b6df35bff4
Revises: 18b0756de278
Create Date: 2026-04-14 01:24:03.758032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8b6df35bff4'
down_revision: Union[str, None] = '18b0756de278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes_pase_masivo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo_serial', sa.String(length=50), nullable=False),
    sa.Column('nombre_evento', sa.String(length=200), nullable=False),
    sa.Column('tipo_pase', sa.Enum('simple', 'identificado', 'portal', name='passe_tipo'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('max_accesos_por_pase', sa.Integer(), nullable=True),
    sa.Column('cantidad_pases', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('zip_generado', sa.Boolean(), nullable=False),
    sa.Column('zip_url', sa.Text(), nullable=True),
    sa.Column('zip_listo_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_pase_masivo_codigo_serial'), 'lotes_pase_masivo', ['codigo_serial'], unique=True)
    op.add_column('codigos_qr', sa.Column('lote_id', sa.UUID(), nullable=True))
    op.add_column('codigos_qr', sa.Column('serial_legible', sa.String(length=50), nullable=True))
    op.add_column('codigos_qr', sa.Column('accesos_usados', sa.Integer(), server_default='0', nullable=False))
    op.add_column('codigos_qr', sa.Column('max_accesos', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'codigos_qr', 'lotes_pase_masivo', ['lote_id'], ['id'], ondelete='CASCADE')
    op.alter_column('entidades_civiles', 'latitud',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='Latitud para ubicación en mapa táctico',
               existing_nullable=True)
    op.alter_column('entidades_civiles', 'longitud',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='Longitud para ubicación en mapa táctico',
               existing_nullable=True)
    op.alter_column('guardias_turno', 'grado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('guardias_turno', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('guardias_turno', 'apellido',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('guardias_turno', 'telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('guardias_turno', 'unidad',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=True)
    op.drop_index('idx_guardias_turno_activo', table_name='guardias_turno', postgresql_where='(activo = true)')
    op.drop_index('idx_guardias_turno_punto', table_name='guardias_turno')
    op.drop_constraint('guardias_turno_punto_id_fkey', 'guardias_turno', type_='foreignkey')
    op.drop_constraint('guardias_turno_usuario_id_fkey', 'guardias_turno', type_='foreignkey')
    op.create_foreign_key(None, 'guardias_turno', 'puntos_acceso', ['punto_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'guardias_turno', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_column('guardias_turno', 'fin_turno')
    op.alter_column('puntos_acceso', 'ubicacion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('puntos_acceso', 'latitud',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='Latitud de la alcabala',
               existing_nullable=True)
    op.alter_column('puntos_acceso', 'longitud',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='Longitud de la alcabala',
               existing_nullable=True)
    op.alter_column('puntos_acceso', 'secret_key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text('md5((random())::text)'))
    op.alter_column('puntos_acceso', 'key_salt',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'BAGFM'::character varying"))
    op.alter_column('puntos_acceso', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('puntos_acceso_usuario_id_key', 'puntos_acceso', type_='unique')
    op.drop_constraint('puntos_acceso_usuario_id_fkey', 'puntos_acceso', type_='foreignkey')
    op.create_foreign_key(None, 'puntos_acceso', 'usuarios', ['usuario_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('solicitudes_evento', 'entidad_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('solicitudes_evento', sa.Column('tipo_pase', sa.Enum('simple', 'identificado', 'portal', name='passe_tipo'), nullable=True))
    op.add_column('solicitudes_evento', sa.Column('lote_id', sa.UUID(), nullable=True))
    op.alter_column('solicitudes_evento', 'solicitado_por',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('solicitudes_evento', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pendiente', 'aprobada', 'aprobada_parcial', 'denegada', name='solicitud_estado', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.create_foreign_key(None, 'solicitudes_evento', 'lotes_pase_masivo', ['lote_id'], ['id'], ondelete='SET NULL')
    op.alter_column('zonas_estacionamiento', 'latitud',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='Latitud central de la zona',
               existing_nullable=True)
    op.alter_column('zonas_estacionamiento', 'longitud',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='Longitud central de la zona',
               existing_nullable=True)
    op.alter_column('zonas_estacionamiento', 'radio_cobertura',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Radio de acción en metros para visualización',
               existing_server_default=sa.text('50'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zonas_estacionamiento', 'radio_cobertura',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Radio de acción en metros para visualización',
               existing_server_default=sa.text('50'))
    op.alter_column('zonas_estacionamiento', 'longitud',
               existing_type=sa.NUMERIC(),
               comment='Longitud central de la zona',
               existing_nullable=True)
    op.alter_column('zonas_estacionamiento', 'latitud',
               existing_type=sa.NUMERIC(),
               comment='Latitud central de la zona',
               existing_nullable=True)
    op.drop_constraint(None, 'solicitudes_evento', type_='foreignkey')
    op.alter_column('solicitudes_evento', 'estado',
               existing_type=sa.Enum('pendiente', 'aprobada', 'aprobada_parcial', 'denegada', name='solicitud_estado', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.alter_column('solicitudes_evento', 'solicitado_por',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('solicitudes_evento', 'lote_id')
    op.drop_column('solicitudes_evento', 'tipo_pase')
    op.drop_constraint(None, 'puntos_acceso', type_='foreignkey')
    op.create_foreign_key('puntos_acceso_usuario_id_fkey', 'puntos_acceso', 'usuarios', ['usuario_id'], ['id'])
    op.create_unique_constraint('puntos_acceso_usuario_id_key', 'puntos_acceso', ['usuario_id'])
    op.alter_column('puntos_acceso', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('puntos_acceso', 'key_salt',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'BAGFM'::character varying"))
    op.alter_column('puntos_acceso', 'secret_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text('md5((random())::text)'))
    op.alter_column('puntos_acceso', 'longitud',
               existing_type=sa.NUMERIC(),
               comment='Longitud de la alcabala',
               existing_nullable=True)
    op.alter_column('puntos_acceso', 'latitud',
               existing_type=sa.NUMERIC(),
               comment='Latitud de la alcabala',
               existing_nullable=True)
    op.alter_column('puntos_acceso', 'ubicacion',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('guardias_turno', sa.Column('fin_turno', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guardias_turno', type_='foreignkey')
    op.drop_constraint(None, 'guardias_turno', type_='foreignkey')
    op.create_foreign_key('guardias_turno_usuario_id_fkey', 'guardias_turno', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('guardias_turno_punto_id_fkey', 'guardias_turno', 'puntos_acceso', ['punto_id'], ['id'])
    op.create_index('idx_guardias_turno_punto', 'guardias_turno', ['punto_id'], unique=False)
    op.create_index('idx_guardias_turno_activo', 'guardias_turno', ['activo'], unique=False, postgresql_where='(activo = true)')
    op.alter_column('guardias_turno', 'unidad',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('guardias_turno', 'telefono',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('guardias_turno', 'apellido',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('guardias_turno', 'nombre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('guardias_turno', 'grado',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('entidades_civiles', 'longitud',
               existing_type=sa.NUMERIC(),
               comment='Longitud para ubicación en mapa táctico',
               existing_nullable=True)
    op.alter_column('entidades_civiles', 'latitud',
               existing_type=sa.NUMERIC(),
               comment='Latitud para ubicación en mapa táctico',
               existing_nullable=True)
    op.drop_constraint(None, 'codigos_qr', type_='foreignkey')
    op.drop_column('codigos_qr', 'max_accesos')
    op.drop_column('codigos_qr', 'accesos_usados')
    op.drop_column('codigos_qr', 'serial_legible')
    op.drop_column('codigos_qr', 'lote_id')
    op.drop_index(op.f('ix_lotes_pase_masivo_codigo_serial'), table_name='lotes_pase_masivo')
    op.drop_table('lotes_pase_masivo')
    # ### end Alembic commands ###
