"""add_manual_fields_to_acceso

Revision ID: e44733fda187
Revises: a128ff455a97
Create Date: 2026-04-24 09:44:58.269185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44733fda187'
down_revision: Union[str, None] = 'a128ff455a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accesos', sa.Column('nombre_manual', sa.String(length=200), nullable=True))
    op.add_column('accesos', sa.Column('cedula_manual', sa.String(length=50), nullable=True))
    op.add_column('accesos', sa.Column('telefono_manual', sa.String(length=50), nullable=True))
    op.add_column('accesos', sa.Column('vehiculo_placa', sa.String(length=20), nullable=True))
    op.add_column('accesos', sa.Column('vehiculo_marca', sa.String(length=50), nullable=True))
    op.add_column('accesos', sa.Column('vehiculo_modelo', sa.String(length=50), nullable=True))
    op.add_column('accesos', sa.Column('vehiculo_color', sa.String(length=50), nullable=True))
    op.add_column('accesos', sa.Column('observaciones', sa.String(length=500), nullable=True))
    
    # Manejo de columna NOT NULL en tabla con datos existentes
    op.add_column('accesos', sa.Column('es_excepcion', sa.Boolean(), nullable=True))
    op.execute("UPDATE accesos SET es_excepcion = FALSE")
    op.alter_column('accesos', 'es_excepcion', nullable=False)
    
    op.create_index(op.f('ix_accesos_vehiculo_placa'), 'accesos', ['vehiculo_placa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accesos_vehiculo_placa'), table_name='accesos')
    op.drop_column('accesos', 'es_excepcion')
    op.drop_column('accesos', 'observaciones')
    op.drop_column('accesos', 'vehiculo_color')
    op.drop_column('accesos', 'vehiculo_modelo')
    op.drop_column('accesos', 'vehiculo_marca')
    op.drop_column('accesos', 'vehiculo_placa')
    op.drop_column('accesos', 'telefono_manual')
    op.drop_column('accesos', 'cedula_manual')
    op.drop_column('accesos', 'nombre_manual')
    # ### end Alembic commands ###
