"""Add_PDF_Url_To_Lote

Revision ID: e68753991495
Revises: 046061ebcb9a
Create Date: 2026-04-18 21:48:33.328850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68753991495'
down_revision: Union[str, None] = '046061ebcb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes_pase_masivo', sa.Column('pdf_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotes_pase_masivo', 'pdf_url')
    # ### end Alembic commands ###
